### PR TITLE
add unordered option to mapping operations via new `ordered: bool` param (closes #18)

### LINKED ISSUE #18: Add unordered concurrent map
When processing a sequence of items, we often want to get the results as soon as possible, without caring about the particular order (we can always enumerate first to recover the order later)

Python multiprocessing.Pool implements this with `imap_unordered` .

API options:

- Add a new `umap()` method
- Add an `ordered` boolean parameter to `map()` and `amap()`

I'm leaning towards the second option. It's more verbose, but easier to read, and removes confusion (e.g. should it be "aumap" or "uamap" etc.)

### PR DESCRIPTION
**Pull request by ebonnal**
With @erezsh (issue #18).

Add optional unordering for faster concurrent `.map`/`.amap`/`.foreach`/`.aforeach` in case of heterogeneously expensive func calls.

### CODE REVIEW

**Comment by erezsh** [comment]
Yes, that looks like the correct behavior.

My one concern is that calling as_completed for each iteration might affect the performance: Every time it's called, it instantiates and appends waiters for each future, and then finally also removes the waiters: https://github.com/python/cpython/blob/4b89c5ebfc7d5d4f008eee0ae6da765dfc28e3a9/Lib/concurrent/futures/_base.py#L251

It may not be a big concern right now, but I can imagine situations in which it would be noticeable. 

The solution would probably be to reimplement as_completed, but as a class (e.g. `class AsCompleted(FuturesManager)`) that maintains state and allows adding new futures.

Anyway, this probably belongs in a separate PR, but I thought it's worth mentioning.

**Comment by ebonnal** [comment]
Oh nice catch! Completely agree we need to get rid of this overhead. I will merge this PR and open an issue. Would be great to tackle this before publishing a release.

(And I can't check now but the async side may have the same issue)

**Comment by erezsh** [comment]
P.S. in the tests, you have a typo in indentity_sleep

**Comment by ebonnal** [comment]
Thanks for the typo catch @erezsh 🙏🏻 

My `next(iter(as_completed(...)))` partial iteration approach was leaky, actually never removing the waiters 😬 so I went for the proper `done_futures, _ = wait(futures, return_when=FIRST_COMPLETED)`.

Here is the follow up issue to reuse waiters #20.

If it sounds good I will merge make a release. Thanks again for collaborating, appreciate it.

**Pull request merged**
